name: koala
description: "KHU's Opensource App for Library Access"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.1.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  hive: ^2.2.3
  flutter_secure_storage: ^9.0.0
  path_provider: ^2.1.2
  june: ^0.8.5
  dio: ^5.4.1
  cookie_jar: ^4.0.8
  dio_cookie_manager: ^3.1.1
  fast_rsa: ^3.6.1
  dynamic_color: ^1.7.0
  qr_flutter: ^4.1.0
  url_launcher: ^6.2.5
  package_info_plus: ^5.0.1
  intl: ^0.19.0
  screen_brightness: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21

flutter:
  assets:
    - assets/images/
    - assets/icon/

  uses-material-design: true